import {
  boolean,
  pgEnum,
  pgTable,
  serial,
  timestamp,
  varchar,
} from 'drizzle-orm/pg-core';
import { InferModel } from 'drizzle-orm';
import { FileType } from '@app/shared/common';

export const typeEnum = pgEnum('file_type', [FileType.IMAGE, FileType.VIDEO]);

export const files = pgTable('files', {
  id: serial('id').primaryKey(),
  hash: varchar('hash').unique().notNull(),
  type: typeEnum('type').notNull(),
  fileName: varchar('file_name').notNull(),
  thumbnailFileName: varchar('thumbnail_file_name'),
  isFavorite: boolean('is_favorite').default(false),
  isArchived: boolean('is_archived').default(false),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at'),
});

export type File = InferModel<typeof files>;
export type NewFile = InferModel<typeof files, 'insert'>;


[
  'SourceFile',
  'errors',
  'tz',
  'tzSource',
  'Orientation',
  'FocalLength',
  'ExifToolVersion',
  'FileName',
  'Directory',
  'FileSize',
  'FileModifyDate',
  'FileAccessDate',
  'FileInodeChangeDate',
  'FilePermissions',
  'FileType',
  'FileTypeExtension',
  'MIMEType',
  'JFIFVersion',
  'ResolutionUnit',
  'XResolution',
  'YResolution',
  'ExifByteOrder',
  'Make',
  'Model',
  'ExposureTime',
  'FNumber',
  'ISO',
  'ExifVersion',
  'OffsetTime',
  'OffsetTimeOriginal',
  'OffsetTimeDigitized',
  'Flash',
  'SubSecTime',
  'SubSecTimeOriginal',
  'SubSecTimeDigitized',
  'ExifImageWidth',
  'ExifImageHeight',
  'WhiteBalance',
  'ProfileCMMType',
  'ProfileVersion',
  'ProfileClass',
  'ColorSpaceData',
  'ProfileConnectionSpace',
  'ProfileDateTime',
  'ProfileFileSignature',
  'PrimaryPlatform',
  'CMMFlags',
  'DeviceManufacturer',
  'DeviceModel',
  'DeviceAttributes',
  'RenderingIntent',
  'ConnectionSpaceIlluminant',
  'ProfileCreator',
  'ProfileID',
  'ProfileDescription',
  'ProfileCopyright',
  'MediaWhitePoint',
  'MediaBlackPoint',
  'RedMatrixColumn',
  'GreenMatrixColumn',
  'BlueMatrixColumn',
  'RedTRC',
  'ChromaticAdaptation',
  'BlueTRC',
  'GreenTRC',
  'ImageWidth',
  'ImageHeight',
  'EncodingProcess',
  'BitsPerSample',
  'ColorComponents',
  'YCbCrSubSampling',
  'Aperture',
  'ImageSize',
  'Megapixels',
  'ShutterSpeed',
  'SubSecCreateDate',
  'SubSecDateTimeOriginal',
  'SubSecModifyDate',
  'CreateDate',
  'DateTimeOriginal',
  'ModifyDate',
  'FocalLength35efl',
  'LightValue'
]